import { fileURLToPath } from 'node:url';
import { devices, expect, test } from '@playwright/test';
import { guestPanel, repoFile, seededExtraction, signIn, signedInPage } from './support';

// The README's three committed screenshots (issue #52), regenerated by
// `pnpm screenshots` — the same seeded harness as `pnpm e2e`, so fixture
// Documents and their Extractions make every run identical. Desktop specs
// share one signed-in page; the mobile shot takes its own iPhone viewport.
const page = signedInPage();

/** Output path under docs/screenshots/ — committed; each run rewrites them. */
const shot = (name: string): string =>
  fileURLToPath(repoFile(`docs/screenshots/${name}.png`));

// Hero shot: an open Document with its Extraction panel — the "Needs your
// attention" Critical Warnings are the product's pitch.
test('reader — a Document open beside its Extraction', async () => {
  await page().goto('/folder/wohnung/doc/doc-mietvertrag');
  await expect(page().getByRole('img', { name: 'Page 1 of 4' })).toBeVisible();

  const panel = guestPanel(page());
  const fixture = seededExtraction('doc-mietvertrag');
  await expect(panel.getByRole('heading', { level: 1, name: 'Mietvertrag 2024' })).toBeVisible();
  await expect(panel.getByText(fixture.plainEnglishSummary)).toBeVisible();
  await expect(panel.getByRole('heading', { name: 'Needs your attention' })).toBeVisible();
  for (const takeaway of fixture.keyTakeaways.filter((t) => t.importance === 'CRITICAL')) {
    await expect(panel.getByText(takeaway.text)).toBeVisible();
  }

  // The seed's one extraction-less Document ("Brief vom Finanzamt") finishes
  // in the background and raises an "is ready" toast — its timing varies with
  // emulator load, so wait out its lifecycle: give it a moment to surface,
  // dismiss whatever shows, then require a clean stack before shooting.
  const statuses = page().getByRole('status');
  await statuses.first().waitFor({ state: 'visible', timeout: 8_000 }).catch(() => {});
  for (const dismiss of await page().getByRole('button', { name: /^Dismiss / }).all()) {
    await dismiss.click();
  }
  await expect(statuses).toBeHidden();

  await page().screenshot({ path: shot('reader'), animations: 'disabled' });
});

// The library: seeded Folder tree expanded in the sidebar.
test('library — the Folder tree with Documents filed', async () => {
  await page().goto('/folder/root');
  await expect(page().getByRole('heading', { level: 1, name: 'Documents' })).toBeVisible();

  await page().getByRole('button', { name: 'Expand Verträge' }).click();
  await page().getByRole('button', { name: 'Expand Versicherungen' }).click();
  await expect(page().getByRole('treeitem', { name: 'Wohnung' })).toBeVisible();
  await expect(page().getByRole('treeitem', { name: 'Internet & Mobilfunk' })).toBeVisible();
  await expect(page().getByRole('treeitem', { name: 'Krankenversicherung' })).toBeVisible();

  await page().screenshot({ path: shot('library'), animations: 'disabled' });
});

// Phone viewport: the reader with the insights sheet resting at peek — grab
// handle and "Insights" header over the unobstructed PDF (issue #50).
test('mobile — the reader with the insights sheet at peek', async ({ browser }) => {
  const mobile = await browser.newPage({ ...devices['iPhone 13'] });
  try {
    await signIn(mobile);
    await mobile.goto('/folder/wohnung/doc/doc-mietvertrag');
    await expect(mobile.locator('.guest-frame-host')).toHaveAttribute('data-sheet', 'peek');
    await expect(mobile.locator('.sheet-handle')).toBeVisible();
    await expect(mobile.locator('.sheet-head')).toHaveText('Insights');
    await expect(mobile.getByRole('img', { name: 'Page 1 of 4' })).toBeVisible();

    await mobile.screenshot({ path: shot('mobile'), animations: 'disabled' });
  } finally {
    await mobile.close();
  }
});
